project:
  type: website

website:
  title: "VRisk.io"
  image: img/logo.png
  favicon: img/logo.png
  page-navigation: true
  bread-crumbs: true
  navbar:
    logo: img/logo.png
    title: false
    search: true
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/owen-vallis-risk-manager
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - Insights.qmd
      - Contact.qmd
  page-footer: 
    left: "Copyright 2024, Owen Vallis"
    right: 
      - icon: linkedin
      href: https://www.linkedin.com/in/owen-vallis-risk-manager

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
    
    


