project:
  type: website

website:
  logo: img/logo.png
  title: "VRisk.io"
  navbar:
  background: primary
  search: true
  tools: 
    - icon: linkedin
      href: https://www.linkedin.com/in/owen-vallis-risk-manager
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



