project:
  type: website

website:
  title: "VRisk.io"
  image: img/logo.png
  favicon: img/logo.png
  page-navigation: true
  navbar:
    logo: img/logo.png
    title: false
    background: light
    search: true
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/owen-vallis-risk-manager
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css
    toc: true
    grid:
      sidebar-width: 250px
      #body-width: 900px
      margin-width: 300px



