project:
  type: website

website:
  title: "VRisk.io"

#  announcement:
#    icon: info-circle
#    dismissable: true
#    content: "**ALERT** - This is some information you should pay attention to"
#    type: primary
#    position: below-navbar

  image: img/logo.png
  favicon: img/logo.png
  twitter-card: true
  open-graph: true
  page-navigation: true
  sidebar:
    logo: img/logo.png
  navbar:
    bread-crumbs: true
    logo: img/logo.png
    title: false
    search: true
    collapse: true
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/owen-vallis-risk-manager
    left:
      - href: index.qmd
        text: Home      
      - href: about.qmd
        text: About
      - Insights.qmd
      - Guides.qmd      
    right:
      - Contact.qmd
  page-footer: 
    right: "Copyright 2024, Owen Vallis"
    center: "Disclaimer: Not Investment Advice! None of the content of this or any other part of this website should in any way be considered investment advice nor does it constitute any offer or solicitation to offer or recommendation of any investment product. Information and opinions presented are for general purposes only and does not take into account your individual needs, investment objectives and specific financial circumstances."
  back-to-top-navigation: true
format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
    css: posts/style.css
