project:
  type: website

website:
  google-analytics: "G-1MM8SPGR75"
  cookie-consent: true
    type: implied
  # policy-url: ""
  title: "VRisk.io"

#  announcement:
#    icon: info-circle
#    dismissable: true
#    content: "**ALERT** - This is some information you should pay attention to"
#    type: primary
#    position: below-navbar

  image: img/logo.png
  favicon: img/logo.png
  twitter-card: true
  open-graph: true
  page-navigation: true
  sidebar:
    logo: img/logo.png
  navbar:
    bread-crumbs: true
    logo: img/logo.png
    title: false
    search: true
    collapse: true
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/owen-vallis-risk-manager
    left:
      - href: index.qmd
        text: Home      
      - href: about.qmd
        text: About
      - Insights.qmd
      - Guides.qmd      
    right:
      - Contact.qmd
      - disclaimer.qmd
  page-footer: 
    right: "Copyright 2024, Owen Vallis"
  back-to-top-navigation: true
format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
    css: posts/style.css
