project:
  type: website

website:
  title: "VRisk.io"
  page-navigation: true
  navbar:
    logo: img/logo.png
    title: false
    background: light
    search: true
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/owen-vallis-risk-manager
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: litera
    css: styles.css
    toc: true



