project:
  type: website

website:
  title: "VRisk.io"

#  announcement:
#    icon: info-circle
#    dismissable: true
#    content: "**ALERT** - This is some information you should pay attention to"
#    type: primary
#    position: below-navbar

  image: img/logo.png
  favicon: img/logo.png
  twitter-card: true
  open-graph: true
  page-navigation: true
  bread-crumbs: true
  navbar:
    logo: img/logo.png
    title: false
    search: true
    collapse: true
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/owen-vallis-risk-manager
    left:
      - href: index.qmd
        text: Home      
      - href: about.qmd
        text: About
      - Insights.qmd
      - href: Pages/HorizonScanning2025.qmd
        text: Horizon Scanning 2025
    right:
      - Contact.qmd
  page-footer: 
    right: "Copyright 2024, Owen Vallis"

format:
  html:
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    toc: true
    
    


